# Config file for Home Assistant

mqtt:
  sensor:
    - name: "Temperature"
      unique_id: "greenhouse_temperature"
      device_class: "temperature"
      state_topic: "greenhouse/temperature"
      state_class: "measurement"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.value }}"
      device: &greenhouse_device
        identifiers: ["greenhouse"]
        name: "Greenhouse"
        model: "Greenhouse v1"
        manufacturer: "Greenhouse Inc."
        sw_version: "1.0.0"
    - name: "Humidity"
      unique_id: "greenhouse_humidity"
      device_class: "humidity"
      state_topic: "greenhouse/humidity"
      state_class: "measurement"
      unit_of_measurement: "%"
      value_template: "{{ value_json.value }}"
      device: *greenhouse_device
    - name: "Soil moisture"
      unique_id: "greenhouse_moisture"
      device_class: "moisture"
      state_topic: "greenhouse/moisture"
      state_class: "measurement"
      unit_of_measurement: "%"
      value_template: "{{ value_json.value }}"
      device: *greenhouse_device
    - name: "Light"
      unique_id: "greenhouse_light_level"
      device_class: "illuminance"
      state_topic: "greenhouse/light_level"
      state_class: "measurement"
      unit_of_measurement: "lx"
      value_template: "{{ value_json.value }}"
      device: *greenhouse_device
  binary_sensor:
    - name: "Motion"
      unique_id: "greenhouse_motion"
      device_class: "motion"
      state_topic: "greenhouse/motion"
      value_template: "{{ value_json.value }}"
      payload_on: "1.00"
      payload_off: "0.00"
      device: *greenhouse_device