name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install make and python3-venv
        run: sudo apt-get update && sudo apt-get install -y make python3-venv
      - name: Setup project
        run: make setup
      - name: Build for target
        run: make build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install make and python3-venv
        run: sudo apt-get update && sudo apt-get install -y make python3-venv
      - name: Setup project
        run: make setup
      - name: Run native tests
        run: make test-native
